---
title: "Teaching Statement"
author: "Jinliang Yang"
date: ""
output: pdf_document
---

---------

1. general principles, mentoring and teaching experience

different levels of teaching

- hand on experience
- project guided
- social media, teaching blog and twitter 

My teaching phyloshpy has been developed during my active involvement in education as a graduate student at Iowa State University. 

I have mentored five undergraduate students.

REU student: 

Honors program participants: Audra Loy  
REU paricipants: Aaron Kusmec, Samantha Roehl  
Lab assistants: Uyen Pham, Talissa Sari  
graduate level: Li Li, Haiying Jiang, guest lecture  

A National Science Foundation (NSF) Research Experiences for Undergraduates (REU), focused on field-based studies of plant conservation genetics.

2. 

3. Interdepartmental. benefit greatly from perspectives provided by other disciplines and believe there is a substantial need for cross-diciplinary training in plant breeding, quantitative genetics, population genetics, statistics and bioinformatics. 

My research and learning process benefited a lot from a across discipline discussion group, including Dr. Dan Nethon and his students for statistical consulation and Dr. Aruru and his students for computational consulation. From basic statistical concepts such as randomazation of experimental design to more complex ones, such as mixed linear model. And also got the efficient computational solutions.

The availability of the enoumous amount of genomic data make the . try to interprate the biological process or hypothesis into mathematical or statistical model. To realize this, in depth understanding of the mathematical or statistical theory is important. 

I will implement the classical genetic concepts into different simulation process. to visualize the process and help students to better understand the biological concepts. At the same time, teaching students to modeling and simulating biological.


to motivate students to learning thing by themselves.

4. Coding and genomics, big data, machine learning.




